source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# unicorn is an HTTP server for Rack applications designed to only serve fast clients on low-latency, high-bandwidth connections and take advantage of features in Unix/Unix-like kernels.
gem 'unicorn', '~> 6.1'

# unicorn-rails overrides the Rack::Handler.default method to return Rack::Handler::Unicorn which will cause rack (and rails) to use unicorn by default.
gem 'unicorn-rails', '~> 2.2', '>= 2.2.1'

# Use webpack to manage app-like JavaScript modules in Rails
gem 'webpacker', '~> 5.4', '>= 5.4.3'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# This gem provides jQuery and the jQuery-ujs driver for your Rails 4+ application
gem 'jquery-rails', '~> 4.4'

# Upload files in your Ruby applications, map them to a range of ORMs, store them on different backends
gem 'carrierwave', '~> 0.11.2'

# Slim is a template language whose goal is reduce the syntax to the essential parts without becoming cryptic
gem 'slim', '~> 3.0', '>= 3.0.6'

# Provides the generator settings required for Rails 3+ to use Slim
gem 'slim-rails', '~> 3.1', '>= 3.1.1'

# Sidekiq Batch Jobs Implementation
gem 'sidekiq-batch', '~> 0.1.3'

# Redis for Ruby on Rails
gem 'redis-rails', '~> 5.0', '>= 5.0.2'

# Kaminari is a Scope & Engine based, clean, powerful, agnostic, customizable and sophisticated paginator for Rails 4+
gem 'kaminari', '~> 1.2', '>= 1.2.2'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

  # RuboCop is a Ruby code style checking and code formatting tool. It aims to enforce the community-driven Ruby Style Guide
  gem 'rubocop', '~> 1.25', '>= 1.25.1'

  # BDD for Ruby
  gem 'rspec', '~> 3.11'

  # rspec-rails is a testing framework for Rails 5+
  gem 'rspec-rails', '~> 5.1'

  # Set of matchers and helpers to allow you test your APIs responses like a pro
  gem 'rspec-json_expectations', '~> 2.2'
end

group :test do
  gem 'database_cleaner-active_record'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  # gem 'rack-mini-profiler', '~> 2.0'
  # gem 'listen', '~> 3.3'
end

