default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresdb
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: nuuvem_development


test:
  <<: *default
  database: nuuvem_test

production:
  <<: *default
  database: nuuvem_production
  username: nuuvem
  password: <%= ENV["NUUVEM_DATABASE_PASSWORD"] %>
